module.exports = {
  kududesign: {
    primary: "#E1296C",
    "primary-focus": "#D31B5D",
    "primary-content": "#fff",
    secondary: "#000",
    "secondary-focus": "#000",
    "secondary-content": "#fff",
    neutral: "#fff",
    "neutral-focus": "#D6D6D6",
    "neutral-content": "#24252B",
    "base-100": "#fff",
    "base-200": "#D6D6D6",
    "base-300": "#24252B",
    "base-content": "#fff",
    info: "#1DA1F2",
    "info-content": "#fff",
    success: "#1ECDBC",
    "success-content": "#fff",
    warning: "#FBBD23",
    "warning-content": "#fff",
    error: "#F87272",
    "error-content": "#fff",
    "--rounded-btn": "0.5rem",
    "--border-btn": "1px",
    "--btn-focus-scale": "",
    "--animation-btn": "",
    "--btn-text-case": "",
    "--animation-input": "0.3s",
  },
};
